# Site settings
title: devanooga
tagline: "A community of tinkerers in and around Chattanooga, TN"
url: "https://devanooga.com"
twitter_username: devanooga
github_username:  devanooga

# Build settings
markdown: kramdown
include: ['_pages']

gems:
  - jekyll-sitemap