# Site settings
title: devanooga
tagline: "An online community of tech enthusiasts in and around Chattanooga,&nbsp;Tennessee."
description: "An online community of tech enthusiasts in and around Chattanooga,&nbsp;Tennessee."
url: "https://devanooga.com"
github_username:  devanooga
logo: /images/devanooga_logo_red.png
pagination: 5
excerpt_separator: "<!--excerpt-->"

# Tag-related settings
tags_dir: /blog/tags
tag_title_prefix: "Posts tagged &ldquo;"
tag_title_suffix: "&rdquo;"

# Build settings
markdown: kramdown
include: ['_pages','_posts']

exclude:
- bin
- design_files
- test
- Rakefile
- readme.md
- vendor

# Default permalink for _posts
permalink: /blog/:year/:month/:day/:title

collections:
  members:
    output: false
    relative_directory: ./_collections/members
  projects:
    output: false
    relative_directory: ./_collections/projects

twitter:
  username: devanooga

social:
  name: devanooga
  links:
    - https://twitter.com/devanooga
    - https://github.com/devanooga
    - https://www.reddit.com/r/devanooga/

sass:
  style: compressed
