name: Netlify Nightly Deploy

on:
  schedule:
    - cron: "0 7 * * *"

jobs:
  build:
    name: Call Netlify build hook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        uses: wei/curl@master
        with:
          args: -X POST -d '{}' "https://api.netlify.com/${{ secrets.NETLIFY_BUILD_HOOK }}"
