name: Netlify Nightly Deploy

on:
  schedule:
    - cron: "30 * * * *"

jobs:
  build:
    name: Call Netlify build hook
    runs-on: ubuntu-latest
    steps:
      - name: Nightly build
        run: curl -s -X POST "https://api.netlify.com/build_hooks/${TOKEN}"
        env:
          TOKEN: ${{ secrets.NETLIFY_BUILD_HOOK_NIGHTLY }}
