name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source
      uses: actions/checkout@v1

    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x

    - name: Install bundler
      run: gem install bundler -v 2.2.19

    - name: Ruby version
      run: ruby -v

    - name: Bundler environment
      run: bundle env

    - name: Install Ruby dependencies
      env:
        BUNDLE_JOBS: 3
        BUNDLE_RETRY: 3
        BUNDLE_DEPLOYMENT: true
      run: bundle check || bundle install

    - name: Build site
      run: bin/jekyll build
    
    - name: Run tests
      run: bin/rake test

    - name: Lint code
      run: bin/rubocop --parallel
